version: '3.8'
services:
  app:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build"
    environment:
      - NODE_ENV=production
    # This service only builds the app

  web:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "5081:5081"
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/app.conf
    # Serves the built app
    networks:
      - portainer_default
# Add external network definition
networks:
  portainer_default:
    external: true
